/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AAutoComplete: typeof import('ant-design-vue/es')['AutoComplete']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    AButtonGroup: typeof import('ant-design-vue/es')['ButtonGroup']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    BankWiseRequisition: typeof import('./src/components/dashboard/BankWiseRequisition.vue')['default']
    ChallanPreviewModal: typeof import('./src/components/orders/ChallanPreviewModal.vue')['default']
    CheckTypeExport: typeof import('./src/components/orders/CheckTypeExport.vue')['default']
    ExportActions: typeof import('./src/components/orders/ExportActions.vue')['default']
    ExportPreviewModal: typeof import('./src/components/orders/ExportPreviewModal.vue')['default']
    FilterSearch: typeof import('./src/components/shared/FilterSearch.vue')['default']
    FilterSelect: typeof import('./src/components/shared/FilterSelect.vue')['default']
    OrderFilters: typeof import('./src/components/orders/OrderFilters.vue')['default']
    OrderHeader: typeof import('./src/components/orders/OrderHeader.vue')['default']
    OrderTable: typeof import('./src/components/orders/OrderTable.vue')['default']
    PreviewTable: typeof import('./src/components/orders/PreviewTable.vue')['default']
    ProgressSection: typeof import('./src/components/orders/ProgressSection.vue')['default']
    RecentActivity: typeof import('./src/components/dashboard/RecentActivity.vue')['default']
    RequisitionStatus: typeof import('./src/components/dashboard/RequisitionStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/dashboard/StatCard.vue')['default']
    UserProfile: typeof import('./src/components/dashboard/UserProfile.vue')['default']
  }
}
