/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BankWiseRequisition: typeof import('./src/components/dashboard/BankWiseRequisition.vue')['default']
    ChallanPreviewModal: typeof import('./src/components/orders/ChallanPreviewModal.vue')['default']
    CheckTypeExport: typeof import('./src/components/orders/CheckTypeExport.vue')['default']
    ExportActions: typeof import('./src/components/orders/ExportActions.vue')['default']
    ExportPreviewModal: typeof import('./src/components/orders/ExportPreviewModal.vue')['default']
    FilterSearch: typeof import('./src/components/shared/FilterSearch.vue')['default']
    FilterSelect: typeof import('./src/components/shared/FilterSelect.vue')['default']
    OrderFilters: typeof import('./src/components/orders/OrderFilters.vue')['default']
    OrderHeader: typeof import('./src/components/orders/OrderHeader.vue')['default']
    OrderTable: typeof import('./src/components/orders/OrderTable.vue')['default']
    PreviewTable: typeof import('./src/components/orders/PreviewTable.vue')['default']
    ProgressSection: typeof import('./src/components/orders/ProgressSection.vue')['default']
    RecentActivity: typeof import('./src/components/dashboard/RecentActivity.vue')['default']
    RequisitionStatus: typeof import('./src/components/dashboard/RequisitionStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/dashboard/StatCard.vue')['default']
    UserProfile: typeof import('./src/components/dashboard/UserProfile.vue')['default']
  }
}
