export default {
  APIs: {
    login: "/api/auth/login",
    logout: "/api/auth/logout",
    validateToken: "/api/auth/validate-token",
    users: "api/users",
    createUserInfo: "/api/user",
    getUserInfo: "/api/user/info",
    getLoggedInUser: "/api/user/loggedin",
    updateUserInfo: "/api/user",
    changePassword: "/api/auth/change-password",
    deleteUser: "/api/user",
    countUser: "/api/user/count",
    menuInfo: "api/Get-menus-by-user",
    routePermission: "api/check-route-permission",
    banks: "/api/banks",
    getVendorForBankInfo: "/api/vendor/getallforbank",
    createBank: "/api/bank",
    updateBank: "/api/bank",
    deleteBank: "/api/bank",
    countBank: "/api/bank/count",
    bankForBranch: "/api/banks/for-branch",
    branches: "/api/branches",
    getVendorForBranchInfo: "/api/vendor/getallforbranch",
    createBranch: "/api/branch",
    updateBranch: "/api/branch",
    deleteBranch: "/api/branch",
    countBranch: "/api/branch/count",
    getBranchForUser: "/api/branch/get-for-user",
    getRoleForUser: "/api/userrole/getallforuser",
    uploadImage: "/api/upload-image",
    localFileUpload: "/api/local-file-upload/bulk",
    createChequeRequisition: "/api/requisition",
    getOrderRequisitions: "/api/requisition/get-all-order-requisitions",
    getOrderRequisitionsForExport:
      "/api/requisition/get-all-order-requisitions-for-export",
    createChallan: "/api/challan/create",
    getChallansExport: "/api/challan/get-challans",
    getDownloadedRequistions: "/api/requisition/get-downloaded-requisitions",
    updateChequeRequisition: "/api/requisition/update-cheque-requisition",
    getAllChallans: "/api/challans",
    fetchChallanItem: "/api/challan/items",
    summaryReport: "/api/summary-report",
    getDashboardStats: "/api/dashboard/statcard",
    getBankRequisitions: "/api/dashboard/bankwiserequisition",
    getOrderTracking: "/api/dashboard/ordertracking",
  },
};
