export default {
  APIs: {
    login: "/api/auth/login",
    logout: "/api/auth/logout",
    register: "/api/auth/register",
    getUserInfo: "/api/user/info",
    updateUserInfo: "/api/user/update",
    changePassword: "/api/user/change-password",
    menuInfo: "api/Get-menus-by-user",
    routePermission: "api/check-route-permission",
    banks: "/api/banks",
    getVendorForBankInfo: "/api/vendor/getallforbank",
    createBank: "/api/bank",
    updateBank: "/api/bank",
    deleteBank: "/api/bank",
    countBank: "/api/bank/count",
    bankForBranch: "/api/banks/for-branch",
    branches: "/api/branches",
    getVendorForBranchInfo: "/api/vendor/getallforbranch",
    createBranch: "/api/branch",
    updateBranch: "/api/branch",
    deleteBranch: "/api/branch",
    countBranch: "/api/branch/count",
  },
};
